In [53]:
import numpy as np

from scipy.sparse import load_npz
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score
import joblib

In [54]:
x = load_npz("../data/ds3_hero_selection.npz")
y = np.load("../data/ds3_match_winner.npy")

# x = x[:10000]
# y = y[:10000]

x_train, x_test, y_train, y_test = train_test_split(x, y, shuffle=True, random_state=42, test_size=0.3)

In [55]:
x.shape

(1635712, 129)

In [56]:
x_test[12].todense()

matrix([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [57]:
y_test[12]

0

In [58]:
x_test.shape

(490714, 129)

In [59]:
clf = MLPClassifier(solver="adam", hidden_layer_sizes=(300,), activation="logistic")
clf.fit(x_train, y_train)

MLPClassifier(activation='logistic', hidden_layer_sizes=(300,))

In [60]:
y_pred = clf.predict(x_test)

In [61]:
accuracy_score(y_test, y_pred)

0.6133919146386694

In [62]:
clf.predict_proba(x_test[1])

array([[0.60913354, 0.39086646]])

In [63]:
confusion_matrix(y_test, y_pred)

array([[ 74875, 132056],
       [ 57658, 226125]])

In [64]:
roc_auc_score(y_test, clf.predict_proba(x_test)[: , 1])

0.6315904107053044

In [65]:
joblib.dump(clf, "../models/mlp_adam_300neurons_logistic_61perc.joblib")

['../models/mlp_adam_300neurons_logistic_61perc.joblib']