In [2]:
import pickle

with open("../training_data/ef5b44b4-0559-4528-97a2-f49b92e0b643_1.pkl", 'rb') as f:
    train_examples = pickle.load(f)




In [22]:
train_examples[2]

(array([-1, -1, -1,  1, -1,  1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0]),
 array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [21]:

import numpy as np
np.abs(train_examples[2][0]).sum()
(train_examples[2][0] == 1).sum()


4

In [55]:
hero_probs = np.random.uniform(0, 1, (5, 5))

hero_probs



array([[0.992837  , 0.79715643, 0.89334062, 0.9342266 , 0.9546553 ],
       [0.92040404, 0.15946335, 0.90285849, 0.99370232, 0.55431708],
       [0.99513539, 0.91490143, 0.5343296 , 0.32830562, 0.97350404],
       [0.87240104, 0.07241972, 0.84803352, 0.1193482 , 0.13521235],
       [0.4261525 , 0.83275989, 0.92244019, 0.23727242, 0.27546679]])

In [57]:
np.argmax(hero_probs, axis=1)

tmp = hero_probs.copy()

print(hero_probs)
for i in range(5):
    hero, pos = np.unravel_index(tmp.argmax(), tmp.shape)
    tmp[hero,:] = -np.inf
    tmp[:,pos] = -np.inf
    print(hero, pos)



[[0.992837   0.79715643 0.89334062 0.9342266  0.9546553 ]
 [0.92040404 0.15946335 0.90285849 0.99370232 0.55431708]
 [0.99513539 0.91490143 0.5343296  0.32830562 0.97350404]
 [0.87240104 0.07241972 0.84803352 0.1193482  0.13521235]
 [0.4261525  0.83275989 0.92244019 0.23727242 0.27546679]]
2 0
1 3
0 4
4 2
3 1
