In [1]:
import scipy as sp
import scipy.sparse
import numpy as np
from numpy.random import default_rng
rng = default_rng()


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, r2_score

In [25]:
hero_selection = sp.sparse.load_npz("../../data/v1/hero_selection_onehot.npz")
match_winner = np.load("../../data/v1/match_winner.npy")


match_winner = (match_winner * 2) - 1
print(hero_selection.shape, match_winner.shape)

(1635712, 256) (1635712,)


In [27]:
match_winner.mean()

0.5777967025980124

In [33]:
# flip random matches
rng_winners = rng.integers(0,2,size=match_winner.shape[0]) 
rng_winners = (rng_winners * 2) - 1

hero_selection[match_winner != rng_winners] = hero_selection[match_winner != rng_winners] * -1
match_winner[match_winner != rng_winners] = match_winner[match_winner != rng_winners] * -1

[0 0 1 ... 0 1 1]


In [34]:
match_winner

array([0, 2, 1, ..., 0, 1, 1], dtype=uint8)

In [12]:
x_train, x_test, y_train, y_test = train_test_split(hero_selection, match_winner, test_size=0.3) 

In [13]:
y_test.mean()

74.29660453950774

In [14]:
clf = LogisticRegression(random_state=21).fit(x_train, y_train)
y_h = clf.predict(x_test)
acc = accuracy_score(y_test, y_h)

print(clf.score(x_test, y_test))


0.7260033339175161


In [15]:
print(r2_score(y_test, y_h))

0.9999172524583394


In [93]:
print(confusion_matrix(y_test, y_h))

[[142783 102461]
 [103358 142112]]


In [95]:
clf.coef_[0, 14]

-0.06001622619265414

## With onehot

In [37]:
hero_selection = sp.sparse.load_npz("../data/hero_selection_onehot.npz")
match_winner = np.load("../data/match_winner.npy")
m_w = np.load("../data/match_winners.npy")

# match_winner = (match_winner * 2) - 1
print(hero_selection.shape, match_winner.shape)

(1635712, 256) (1635712,)


In [38]:
match_winner[:10]

array([0, 1, 0, 0, 1, 0, 1, 1, 1, 0], dtype=uint8)

In [39]:
m_w[:10]

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1])

In [40]:
match_winner.mean()

0.5777967025980124

In [49]:
# flip random matches
rng_winners = rng.integers(0,2,size=match_winner.shape[0]) 
rng_winners = (rng_winners * 2) - 1

hero_selection[match_winner != rng_winners] = hero_selection[match_winner != rng_winners] * -1
match_winner[match_winner != rng_winners] = match_winner[match_winner != rng_winners] * -1
match_winner[:10]

array([  0,   1,   0,   0,   1,   0, 255, 255, 255,   0], dtype=uint8)

In [42]:
x_train, x_test, y_train, y_test = train_test_split(hero_selection, match_winner, test_size=0.3, random_state=42, shuffle=True) 

In [44]:
y_test.mean()

73.70409851767018

In [43]:
clf = LogisticRegression().fit(x_train, y_train)
y_h = clf.predict(x_test)
acc = accuracy_score(y_test, y_h)

print(clf.score(x_test, y_test))


0.7266819369327143


/home/bao/anaconda3/envs/dota-scraper/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
print(r2_score(y_test, y_h))

0.9999129339056552


In [13]:
print(confusion_matrix(y_test, y_h))

[[313081  35706]
 [105956  35971]]


In [14]:
clf.coef_[0, 14]

0.07544517771391919