In [1]:
import numpy as np

from scipy.sparse import load_npz
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score
import joblib

In [2]:
x = load_npz("../data/ds4_hero_selection.npz")
y = np.load("../data/ds4_match_winner.npy")

# x = x[:10000]
# y = y[:10000]

x_train, x_test, y_train, y_test = train_test_split(x, y, shuffle=True, random_state=42, test_size=0.3)

In [3]:
x.shape

(2162047, 119)

In [4]:
x_test[12].todense()

matrix([[ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0., -1.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
          1.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.]])

In [10]:
y_test[11]

1

In [11]:
x_test.shape

(648615, 119)

In [12]:
clf = MLPClassifier(solver="adam", hidden_layer_sizes=(300,), activation="logistic")
clf.fit(x_train, y_train)

MLPClassifier(activation='logistic', hidden_layer_sizes=(300,))

In [13]:
y_pred = clf.predict(x_test)

In [14]:
accuracy_score(y_test, y_pred)

0.6119639539634452

In [15]:
clf.predict_proba(x_test[1])

array([[0.56318099, 0.43681901]])

In [16]:
confusion_matrix(y_test, y_pred)

array([[ 87614, 186872],
       [ 64814, 309315]])

In [17]:
roc_auc_score(y_test, clf.predict_proba(x_test)[: , 1])

0.6314990347239412

In [19]:
joblib.dump(clf, "../models/mlp_adam_300neurons_logistic_61perc.joblib")

['../models/mlp_adam_300neurons_logistic_61perc.joblib']